Cast idle_time_in_msec to appropriate type
-Werror is used but newer gcc have a new check, and it makes the
compilation fail with gpm-idle.c:295: error: format ‘%lld’ expects type
‘long long int’, but argument 5 has type ‘gint64’