Re-enable deprecated GDK functions for brightness applet
brightness-applet.c: In function ‘gpm_applet_draw_cb’:
brightness-applet.c:282: warning: implicit declaration of function ‘gdk_gc_new’
brightness-applet.c:282: warning: assignment makes pointer from integer without a cast
brightness-applet.c:288: warning: implicit declaration of function ‘gdk_draw_drawable’
brightness-applet.c:293: warning: implicit declaration of function ‘gdk_gc_set_rgb_fg_color’
brightness-applet.c:294: warning: implicit declaration of function ‘gdk_gc_set_fill’
brightness-applet.c:295: warning: implicit declaration of function ‘gdk_draw_rectangle’
brightness-applet.c:307: warning: implicit declaration of function ‘gdk_draw_pixbuf’

The long-term fix is to port the applet from gdk_gc_* to cairo, but implicit
pointer conversions cause crashes on x86_64 platforms, so re-enable the
functions for now.