brightness-applet: Add missing include
brightness-applet.c: In function ‘main’:
brightness-applet.c:1026: warning: implicit declaration of function ‘unsetenv’

Include <stdlib.h> to fix this.